### ISSUE TITLE
gradle jettyRun on zuul-simple-webapp fails with ClassCastException

### ISSUE THREAD

**Issue by jinnah79** [Netflix/zuul#104]
I am running this in Windows 7 machine. Following is the stacktrace.
FAILURE: Build failed with an exception.

* Where:
Script 'D:\Projects\HA Architecture\Tools\zuul-1.x\zuul-1.x\gradle\convention.gradle' line: 27

* What went wrong:
A problem occurred evaluating script.
> java.lang.String cannot be cast to org.gradle.api.artifacts.Configuration

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating script.
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:54)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:148)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyScript(DefaultObjectConfigurationAction.java:93)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$000(DefaultObjectConfigurationAction.java:36)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$1.run(DefaultObjectConfigurationAction.java:62)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:131)
        at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:37)
        at org.gradle.api.Project$apply$0.call(Unknown Source)
        at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.groovy:34)
        at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
        at build_387zevgzfkz174674edbyc6aq.run(D:\Projects\HA Architecture\Tools\zuul-1.x\zuul-1.x\build.gradle:13)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:52)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:148)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:59)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:504)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:83)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:129)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to org.gradle.api.artifacts.Configuration
        at org.gradle.api.artifacts.Configuration$Namer.determineName(Configuration.java:87)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.add(DefaultNamedDomainObjectCollection.java:70)
        at org.gradle.api.NamedDomainObjectCollection$add.call(Unknown Source)
        at convention_cb8mrdarz5v6qz4tjgsw6v14o$_run_closure1.doCall(D:\Projects\HA Architecture\Tools\zuul-1.x\zuul-1.x\gradle\convention.gradle:27)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:63)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:91)
        at org.gradle.api.internal.project.AbstractProject.configure(AbstractProject.java:824)
        at org.gradle.api.internal.project.AbstractProject.configure(AbstractProject.java:829)
        at org.gradle.api.internal.project.AbstractProject.subprojects(AbstractProject.java:812)
        at org.gradle.api.internal.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:225)
        at org.gradle.api.internal.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:129)
        at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:147)
        at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
        at convention_cb8mrdarz5v6qz4tjgsw6v14o.run(D:\Projects\HA Architecture\Tools\zuul-1.x\zuul-1.x\gradle\convention.gradle:5)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:52)
        ... 43 more

BUILD FAILED

Total time: 3.651 secs

**Comment by osoguru** [comment]
This is most likely due to Zuul using gradle 1.x for builds. The build scripts haven't been updated for gradle 2.0. Try using the included wrapper (gradlew.bat) to build instead of your local gradle install.

**Comment by bnagarajan** [comment]
I am using mac for build zuul. I am getting the same exception. Can you please let me know if there is any way apart from downgrading gradle?

**Comment by bnagarajan** [comment]
Just as an alternative, downgraded gradle version in mac - using below command and build the project,

cd $(brew --prefix)
brew versions gradle
## copy and run the git checkout for your desired gradle version
brew unlink gradle
brew install gradle

**Comment by jinnah79** [comment]
I think that it is a gradle version issue. When i clone the project using git instead of zip download, the issue got resolved. Git clone might brought the inbuild gradle.


Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: bnagarajan <notifications@github.com> </div><div>Date:21/02/2015  11:55 PM  (GMT+05:30) </div><div>To: Netflix/zuul <zuul@noreply.github.com> </div><div>Cc: jinnah79 <kma_jinnahm@yahoo.com> </div><div>Subject: Re: [zuul] gradle jettyRun on zuul-simple-webapp fails with
  ClassCastException (#104) </div><div>
</div>I am using mac for build zuul. I am getting the same exception. Can you please let me know if there is any way apart from downgrading gradle?

**Comment by jinnah79** [comment]
Hi jincy,
Pagination parameter is not applicable for calendar view. Consider this in your search method. Introduce "MonitoringViewType" as enum with GRID_VIEW, CALENDAR_VIEW as values and put it in searchto and use it in the query construction logic.

Regards,
Jinnah


Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: kma_jinnahm <kma_jinnahm@yahoo.com> </div><div>Date:22/02/2015  12:41 AM  (GMT+05:30) </div><div>To: Netflix/zuul <reply@reply.github.com>,Netflix/zuul <zuul@noreply.github.com> </div><div>Subject: Re: [zuul] gradle jettyRun on zuul-simple-webapp fails with
  ClassCastException (#104) </div><div>
</div>I think that it is a gradle version issue. When i clone the project using git instead of zip download, the issue got resolved. Git clone might brought the inbuild gradle.


Sent from Samsung Mobile
