### ISSUE TITLE
java.lang.ClassCastException: com.netflix.loadbalancer.Server cannot be cast to com.netflix.niws.loadbalancer.DiscoveryEnabledServer

### ISSUE THREAD

**Issue by h3xstream** [Netflix/zuul#1137]
I'm trying to test a basic setup of Zuul and I can't make the sample server work..

```
2021-11-16 00:45:39,882 WARN  com.netflix.zuul.filters.endpoint.ProxyEndpoint [Salamander-ClientToZuulWorker-0] FAILURE_LOCAL, origin = OriginName{niwsClientName='api', target='api', authority='api'}, origin channel info = 
java.lang.ClassCastException: com.netflix.loadbalancer.Server cannot be cast to com.netflix.niws.loadbalancer.DiscoveryEnabledServer
	at com.netflix.zuul.discovery.DynamicServerResolver.resolve(DynamicServerResolver.java:56) ~[zuul-discovery-2.3.1-SNAPSHOT.jar:2.3.1-SNAPSHOT]
	at com.netflix.zuul.discovery.DynamicServerResolver.resolve(DynamicServerResolver.java:42) ~[zuul-discovery-2.3.1-SNAPSHOT.jar:2.3.1-SNAPSHOT]
	at com.netflix.zuul.netty.connectionpool.DefaultClientChannelManager.acquire(DefaultClientChannelManager.java:328) ~[zuul-core-2.3.1-SNAPSHOT.jar:2.3.1-SNAPSHOT]
```
I'm probably missing something for my configuration.

My configuration:
```
zuul.server.port.main=9500

### Load balancing backends without Eureka
eureka.shouldFetchRegistry=false
eureka.validateInstanceId=false
eureka.shouldUseDns=false

api.ribbon.listOfServers=127.0.0.1:9090
api.ribbon.client.NIWSServerListClassName=com.netflix.loadbalancer.ConfigurationBasedServerList
api.ribbon.readTimeout=10000
routes.api.path=/api/**
```

**Comment by argha-c** [comment]
Please [try the workaround suggested here](https://github.com/Netflix/zuul/issues/1075#issuecomment-882804035)
