### ISSUE TITLE
Unable to run latest zuul-simple-webapp in tomcat.

### ISSUE THREAD

**Issue by jusroberts** [Netflix/zuul#128]
Hi,

We have been using Zuul since April, and the version we grabbed on April 9th had worked perfectly with tomcat 7. However, when trying to upgrade to the latest commits from upstream, we've run into an issue that doesn't occur in `../gradlew jettyRun`, but does occur in Tomcat 7: when the routing filter attempts to reach out to apache.org [here](https://github.com/Netflix/zuul/blob/1.x/zuul-simple-webapp/src/main/groovy/filters/route/SimpleHostRequest.groovy#L234), an exception occurs because the InputStream seems to be empty (`inputStream.available()` returns 0). 

The debug trace shows the error thusly: 
`ZUUL_DEBUG::Running Filter failed SimpleHostRoutingFilter type:route order:100 Stream closed`

Has anyone else seen this or knows of a work around? This issue may be related to #33. 

Debug:
```
ZUUL_DEBUG::Filter pre 5 PreDecorationFilter
ZUUL_DEBUG::Filter {PreDecorationFilter TYPE:pre ORDER:5} Execution time = 27ms
ZUUL_DEBUG::{PreDecorationFilter} added originResponseHeaders=[com.netflix.util.Pair@64edca63]
ZUUL_DEBUG::{PreDecorationFilter} added routeHost=http://apache.org/
ZUUL_DEBUG::{PreDecorationFilter} changed executedFilters=DebugFilter[SUCCESS][34ms], PreDecorationFilter[SUCCESS][27ms]
ZUUL_DEBUG::Filter pre 10000 DebugRequest
ZUUL_DEBUG::Filter {DebugRequest TYPE:pre ORDER:10000} Execution time = 39ms
ZUUL_DEBUG::{DebugRequest} changed executedFilters=DebugFilter[SUCCESS][34ms], PreDecorationFilter[SUCCESS][27ms], DebugRequest[SUCCESS][39ms]
ZUUL_DEBUG::Filter pre 50000
ZUUL_DEBUG::Filter { TYPE:pre ORDER:50000} Execution time = 4ms
ZUUL_DEBUG::{} added javaPreFilter-ran=true
ZUUL_DEBUG::{} changed executedFilters=DebugFilter[SUCCESS][34ms], PreDecorationFilter[SUCCESS][27ms], DebugRequest[SUCCESS][39ms], [SUCCESS][4ms]
ZUUL_DEBUG::Invoking {route} type filters
ZUUL_DEBUG::Filter route 100 SimpleHostRoutingFilter
ZUUL_DEBUG::Running Filter failed SimpleHostRoutingFilter type:route order:100 Stream closed
ZUUL_DEBUG::Invoking {error} type filters
ZUUL_DEBUG::Invoking {post} type filters
ZUUL_DEBUG::Filter post 1000 SendResponseFilter
ZUUL_DEBUG::Filter post 2000 Stats
REQUEST_DEBUG::REQUEST:: http 0:0:0:0:0:0:0:1:52160
REQUEST_DEBUG::REQUEST:: > GET / HTTP/1.1
REQUEST_DEBUG::REQUEST:: > host:localhost:8080
REQUEST_DEBUG::REQUEST:: > connection:keep-alive
REQUEST_DEBUG::REQUEST:: > cache-control:max-age=0
REQUEST_DEBUG::REQUEST:: > accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
REQUEST_DEBUG::REQUEST:: > user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36
REQUEST_DEBUG::REQUEST:: > accept-encoding:gzip, deflate, sdch
REQUEST_DEBUG::REQUEST:: > accept-language:en-US,en;q=0.8
REQUEST_DEBUG::REQUEST:: > if-none-match:"bb15-519476ad19809"
REQUEST_DEBUG::REQUEST:: > if-modified-since:Wed, 24 Jun 2015 18:10:09 GMT
REQUEST_DEBUG::REQUEST:: >
REQUEST_DEBUG::ZUUL:: host=http://apache.org/
REQUEST_DEBUG::ZUUL::> host  localhost:8080
REQUEST_DEBUG::ZUUL::> connection  keep-alive
REQUEST_DEBUG::ZUUL::> cache-control  max-age=0
REQUEST_DEBUG::ZUUL::> accept  text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
REQUEST_DEBUG::ZUUL::> user-agent  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36
REQUEST_DEBUG::ZUUL::> accept-language  en-US,en;q=0.8
REQUEST_DEBUG::ZUUL::> if-none-match  "bb15-519476ad19809"
REQUEST_DEBUG::ZUUL::> if-modified-since  Wed, 24 Jun 2015 18:10:09 GMT
REQUEST_DEBUG::ZUUL:: > GET  / HTTP/1.1
```

Stack Trace (the line number is slightly off due to spitting out this message):
```
java.io.IOException: Stream closed
	at org.apache.catalina.connector.InputBuffer.read(InputBuffer.java:312)
	at org.apache.catalina.connector.CoyoteInputStream.read(CoyoteInputStream.java:200)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.read1(BufferedReader.java:210)
	at java.io.BufferedReader.read(BufferedReader.java:286)
	at java.io.Reader.read(Reader.java:140)
	at org.codehaus.groovy.runtime.IOGroovyMethods.getText(IOGroovyMethods.java:863)
	at org.codehaus.groovy.runtime.IOGroovyMethods.getText(IOGroovyMethods.java:814)
	at org.codehaus.groovy.runtime.dgm$686.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at SimpleHostRoutingFilter.debugRequestEntity(SimpleHostRequest.groovy:239)
	at SimpleHostRoutingFilter$debugRequestEntity$5.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at SimpleHostRoutingFilter.debug(SimpleHostRequest.groovy:229)
	at SimpleHostRoutingFilter$debug$4.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at SimpleHostRoutingFilter.forward(SimpleHostRequest.groovy:246)
	at SimpleHostRoutingFilter$forward$3.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at SimpleHostRoutingFilter.run(SimpleHostRequest.groovy:203)
	at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:112)
	at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:197)
	at com.netflix.zuul.FilterProcessor.runFilters(FilterProcessor.java:161)
	at com.netflix.zuul.FilterProcessor.route(FilterProcessor.java:120)
	at com.netflix.zuul.ZuulRunner.route(ZuulRunner.java:96)
	at com.netflix.zuul.http.ZuulServlet.route(ZuulServlet.java:119)
	at com.netflix.zuul.http.ZuulServlet.service(ZuulServlet.java:84)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.netflix.zuul.context.ContextLifecycleFilter.doFilter(ContextLifecycleFilter.java:40)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:957)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by manuelcorrea** [comment]
@jusroberts we got ours working  in tomcat8 by adding 

```
<servlet>
         <servlet-name>ZuulServlet</servlet-name>
         <servlet-class>com.netflix.zuul.http.ZuulServlet</servlet-class>
        <init-param>
          <param-name>buffer-requests</param-name>
           <param-value>true</param-value>
       </init-param>
     </servlet>
```

**Comment by jusroberts** [comment]
Thanks, I'll try that!

**Comment by jusroberts** [comment]
Editing web.xml with this fix worked! thanks for the help @manuelcorrea
