### ISSUE TITLE
Runtime issues with asm dependencies

### ISSUE THREAD

**Issue by jharen** [Netflix/zuul#143]
Hello all,
I'm getting a slew of runtime errors around versions of asm being pulled in from transitive dependencies. Namely, I pull fresh from mainline, build, then run > ../gradlew jettyRun. I get the exception:
failed ContextHandlerCollection@783f4ac3: java.lang.IncompatibleClassChangeError: class com.netflix.governator.lifecycle.AnnotationFinder has interface org.objectweb.asm.ClassVisitor as super class
failed HandlerCollection@363d12bd: java.lang.IncompatibleClassChangeError: class com.netflix.governator.lifecycle.AnnotationFinder has interface org.objectweb.asm.ClassVisitor as super class
Error starting handlers
java.lang.IncompatibleClassChangeError: class com.netflix.governator.lifecycle.AnnotationFinder has interface org.objectweb.asm.ClassVisitor as super class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at org.mortbay.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:392)
	at org.mortbay.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:363)
	at com.netflix.governator.lifecycle.ClasspathScanner.doScanning(ClasspathScanner.java:154)
	at com.netflix.governator.lifecycle.ClasspathScanner.<init>(ClasspathScanner.java:78)
	at com.netflix.governator.lifecycle.ClasspathScanner.<init>(ClasspathScanner.java:58)
	at com.netflix.governator.guice.LifecycleInjector.createStandardClasspathScanner(LifecycleInjector.java:285)
	at com.netflix.karyon.server.ServerBootstrap.initialize(ServerBootstrap.java:114)
	at com.netflix.karyon.server.KaryonServer.<init>(KaryonServer.java:166)
	at com.netflix.karyon.server.KaryonServer.<init>(KaryonServer.java:138)
	at com.netflix.zuul.StartServer.<init>(StartServer.java:84)
...

Hmm, ok. To see what's going on, I run
../gradlew --daemon dependencyInsight --dependency asm
Inferred version: 1.1.0-SNAPSHOT
...
:zuul-netflix-webapp:dependencyInsight
asm:asm:3.1
\--- com.sun.jersey:jersey-server:1.17.1
     +--- compile
     +--- com.sun.jersey:jersey-servlet:1.17.1
     |    \--- compile
     +--- com.netflix.pytheas:pytheas-core:1.11
     |    +--- com.netflix.karyon:karyon-admin:2.0.02
     |    |    +--- compile
     |    |    \--- com.netflix.karyon:karyon-admin-web:2.0.02
     |    |         \--- compile
     |    \--- com.netflix.karyon:karyon-admin-web:2.0.02 (*)
     \--- com.sun.jersey.contribs:jersey-guice:1.9.1
          +--- com.netflix.karyon:karyon-admin:2.0.02 (*)
          \--- com.netflix.pytheas:pytheas-core:1.11 (*)

org.ow2.asm:asm:5.0.4
\--- com.netflix.governator:governator:1.9.2
     +--- com.netflix.pytheas:pytheas-core:1.11
     |    +--- com.netflix.karyon:karyon-admin:2.0.02
     |    |    +--- compile
     |    |    \--- com.netflix.karyon:karyon-admin-web:2.0.02
     |    |         \--- compile
     |    \--- com.netflix.karyon:karyon-admin-web:2.0.02 (*)
     \--- com.netflix.karyon:karyon-spi:2.0.02
          \--- com.netflix.karyon:karyon-eureka:2.0.02
               \--- com.netflix.karyon:karyon-core:2.0.02
                    +--- compile
                    \--- com.netflix.karyon:karyon-admin:2.0.02 (*)

(*) - dependencies omitted (listed previously)

Huh, that don't look right. asm 3.1 is as old as the hills, and two versions shouldn't be there anyway(?). Let's exclude that and use gradle-dependency-lock to force everything to 5.0.4. Now I get:
dependencyInsight
org.ow2.asm:asm:5.0.4 (forced)
\--- com.netflix.governator:governator:1.9.2
     +--- com.netflix.governator:governator-archaius:1.9.2
     |    \--- compile
     +--- com.netflix.pytheas:pytheas-core:1.11
     |    +--- com.netflix.karyon:karyon-admin:2.0.02
     |    |    +--- compile
     |    |    \--- com.netflix.karyon:karyon-admin-web:2.0.02
     |    |         \--- compile
     |    \--- com.netflix.karyon:karyon-admin-web:2.0.02 (*)
     \--- com.netflix.karyon:karyon-spi:2.0.02
          \--- com.netflix.karyon:karyon-eureka:2.0.02
               \--- com.netflix.karyon:karyon-core:2.0.02
                    +--- compile
                    \--- com.netflix.karyon:karyon-admin:2.0.02 (*)

org.ow2.asm:asm:latest.release -> 5.0.4
\--- compile

(*) - dependencies omitted (listed previously)

...ok, looks better. But when I run it:
failed ContextHandlerCollection@60411470: java.lang.Error: java.lang.reflect.InvocationTargetException
failed HandlerCollection@6913f234: java.lang.Error: java.lang.reflect.InvocationTargetException
Error starting handlers
java.lang.Error: java.lang.reflect.InvocationTargetException
	at com.netflix.governator.guice.InternalLifecycleModule.processInjectedObject(InternalLifecycleModule.java:104)
	at com.netflix.governator.guice.InternalLifecycleModule.access$000(InternalLifecycleModule.java:44)
	at com.netflix.governator.guice.InternalLifecycleModule$2$1.afterInjection(InternalLifecycleModule.java:76)
	at com.google.inject.internal.MembersInjectorImpl.notifyListeners(MembersInjectorImpl.java:119)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:115)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
	at com.netflix.karyon.server.lifecycle.ServerInitializer.initialize(ServerInitializer.java:74)
	at com.netflix.karyon.server.KaryonServer.start(KaryonServer.java:201)
	at com.netflix.zuul.StartServer.contextInitialized(StartServer.java:103)
...
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.netflix.governator.lifecycle.LifecycleManager.startInstance(LifecycleManager.java:342)
	at com.netflix.governator.lifecycle.LifecycleManager.add(LifecycleManager.java:155)
	at com.netflix.governator.guice.InternalLifecycleModule.processInjectedObject(InternalLifecycleModule.java:101)
	... 101 more
Caused by: java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at org.mortbay.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:392)
	at org.mortbay.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:363)
	at com.sun.jersey.api.core.ScanningResourceConfig.init(ScanningResourceConfig.java:79)
	at com.sun.jersey.api.core.PackagesResourceConfig.init(PackagesResourceConfig.java:104)
	at com.sun.jersey.api.core.PackagesResourceConfig.<init>(PackagesResourceConfig.java:78)
	at com.sun.jersey.api.core.PackagesResourceConfig.<init>(PackagesResourceConfig.java:89)
	at com.netflix.adminresources.AdminResourcesFilter.getDefaultResourceConfig(AdminResourcesFilter.java:72)
	at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.getDefaultResourceConfig(ServletContainer.java:325)
...

Setting a breakpoint to catch the error, I see that it's always thrown when loading com.sun.jersey.core.spi.scanning.uri.JarZipSchemeScanner. For what it's worth, jersey-core is resolving to 1.19.

At this point I'm running out of ideas. At first I was compiling and running with JDK8, but I switched to 7 and the behavior is exactly the same.

Anyone seen anything like this?

**Comment by jharen** [comment]
Blargh, nevermind. jersey-servlet and jersey-client were mismatched. Locking them all to 1.19 fixed this issue.

**Comment by obila007** [comment]
How did you solve this problem, I have the same. can you share your solution please :)

**Comment by kerumai** [comment]
FYI - I've committed a fix for this jersey and asm problem to 1.x now - e5aaa555520875a159274bf80c1d4d67ac5e1021
