### ISSUE TITLE
 Error in Zuul SendErrorFilter during forward to errorPath

### ISSUE THREAD

**Issue by tcesenthil** [Netflix/zuul#151]
When my Zuul Filter is unable to route to a configured URL, the 'RibbonRoutingFilter' class throws a ZuulException saying "Forwarding error" and the control goes to the 'SendErrorFilter' class.

Now when the SendErrorFilter class tries to do a forward, another exception happens during this forward call.

```
dispatcher.forward(ctx.getRequest(), ctx.getResponse());
```

The exception happening during this forward call is

```
Caused by: java.lang.IllegalArgumentException: UT010023: Request org.springframework.cloud.netflix.zuul.filters.pre.Servlet30WrapperFilter$Servlet30RequestWrapper@6dc974ea was not original or a wrapper
    at io.undertow.servlet.spec.RequestDispatcherImpl.forward(RequestDispatcherImpl.java:103) ~[undertow-servlet-1.1.3.Final.jar:1.1.3.Final]
    at org.springframework.cloud.netflix.zuul.filters.post.SendErrorFilter.run(SendErrorFilter.java:74) ~[spring-cloud-netflix-core-1.0.0.RELEASE.jar:1.0.0.RELEASE]
    at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:112) ~[zuul-core-1.0.28.jar:na]
    at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:197) ~[zuul-core-1.0.28.jar:na]
```

Finally when the control comes to my custom ZuulErrorFilter , i do not get the original exception. Instead the exception object i get is the one that occurs during the forward.

If the errorPathis not configured, Zuul by default looks for a service named /error and tries to dispatch to that service. Since we did not have any service for /error , the dispatcher.forward() was throwing error.

How can we skip this fwd to an error handling service ? We have a ErrorFilter to log the error. We do not want to have a error handling service.

**Comment by spencergibb** [comment]
You should probably log this in https://github.com/spring-cloud/spring-cloud-netflix/issues
