### ISSUE TITLE
411 Content Length required issue

### ISSUE THREAD

**Issue by beku8** [Netflix/zuul#223]
For some reason, my home ISP throws ```411 Content length required``` error when I try to post something to the cloud rest endpoint thru locally running zuul proxy. 
So I tried setting ```content-length``` header manually from a custom filter like:
```ctx.addZuulRequestHeader("content-length", ctx.getRequest().getHeader("Content-Length"));```

But it throws 
```
com.netflix.zuul.exception.ZuulException: Forwarding error...
Caused by: org.apache.http.ProtocolException: Content-Length header already present
	at org.apache.http.protocol.RequestContent.process(RequestContent.java:95)
	at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:131)
	at org.apache.http.protocol.HttpRequestExecutor.preProcess(HttpRequestExecutor.java:165)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:485)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
```

I'm using Zuul 1.0.28. Am I doing anything wrong? I'm not even sure if the original problem would disappear if I manage to set this header manually. Any suggestion, anything would be very much appreciated.

p.s: ISP allows my post request when its done thru Feign.

**Comment by kerumai** [comment]
You should not need to set the Content-Length header in a filter because apache httpclient should be setting it itself. And as you found out, it will throw an error if you try to set it yourself.

So we need to find out if for some reason the header is _not_ getting sent from Zuul. So can you try either:
1. Enable apache httpclient debug logging (log4j.logger.org.apache.http=DEBUG - https://hc.apache.org/httpcomponents-client-ga/logging.html), which will then log exactly what headers are being sent over the wire. And therefore see if Content-Length is being sent.
2. Configure zuul to proxy to http://httpbin.org/post and then see if it is receiving the Content-Length header.

**Comment by txomon** [comment]
I am getting this error too with the latest zuul `com.netflix.zuul:zuul-core:1.2.0`, with the scripts in master. But it only happens when proxying under certain conditions. @beku8 did you get to solve it?

**Comment by beku8** [comment]
@kerumai Thanks for the tip. I'm using spring cloud, which provides a "trace" endpoint. 
Here's the request from browser to the server:
```
info: {
  method: "PUT",
  path: "/api/core/rest/location/amarbayasgalant",
  headers: {
    request: {
      host: "localhost:9000",
      connection: "keep-alive",
      content-length: "663",
      pragma: "no-cache",
      cache-control: "no-cache",
      authorization: "...authorization omitted",
      accept: "application/json, text/plain, */*",
      origin: "http://localhost:9000",
      user-agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.63 Safari/537.36",
      content-type: "application/json;charset=UTF-8",
      referer: "http://localhost:9000/manage/mn/reference/location",
      accept-encoding: "gzip, deflate, sdch",
      accept-language: "en-US,en;q=0.8,bg;q=0.6,ru;q=0.4",
      cookie: "....cookie values omitted..."
    },
    response: {...response omitted...}
  }
}
```
Well it this point browser sends the content-length properly, but from zuul server to the microservice, content-length is not being sent.

```
info: {
  method: "PUT",
  path: "/rest/location/amarbayasgalant",
  query: "?_t=mn",
  remote: true,
  proxy: "api/core",
  headers: {
    request: {
      accept: "application/json, text/plain, */*",
      origin: "http://localhost:9000",
      user-agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.63 Safari/537.36",
      content-type: "application/json;charset=UTF-8",
      referer: "http://localhost:9000/manage/mn/reference/location",
      accept-language: "en-US,en;q=0.8,bg;q=0.6,ru;q=0.4",
      authorization: "...Bearer token omitted",
      x-forwarded-host: "localhost",
      x-forwarded-proto: "http",
      x-forwarded-prefix: "/api/core",
      x-forwarded-port: "9000",
      x-forwarded-for: "127.0.0.1",
      Accept-Encoding: "gzip"
    },
    response: {
      Server: "httppd",
      Date: "Wed, 15 Jun 2016 11:30:35 GMT",
      Content-Type: "text/html",
      Content-Length: "3892",
      Connection: "close",
      status: "411"
    }
  },
  body: "... json body omitted"
}
```

I'm using spring cloud project which configures zuul under the hood, its probably a problem with spring cloud?

**Comment by beku8** [comment]
I just created a very simple demo app https://github.com/beku8/zuul-411 here, which just posts empty body to a httpbin.org using zuul. Simple spring-boot/cloud app you can run maven or eclipse. if you checkout out the /trace endpoint: same issue, no content-length being set.

I think because most of the ISPs don't "require" content-length, this issue was not looked at before.

**Comment by kerumai** [comment]
Thanks for taking the time to make that https://github.com/beku8/zuul-411 repo @beku8 . That made it a lot easier for me to debug.

But when I run it, the Content-Type header **does** get sent according to httpbin. Here's the output from me doing a curl against your zuul-411 project:

```bash
$ curl -X PUT --data-ascii "blah" -H "Content-Type: text/plain" http://localhost:8080/api/httpbin/put
{
  "args": {},
  "data": "blah",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "*/*",
    "Accept-Encoding": "gzip",
    "Content-Length": "4",
    "Content-Type": "text/plain",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.48.0",
    "X-Forwarded-Host": "localhost",
    "X-Forwarded-Prefix": "/api/httpbin"
  },
  "json": null,
  "origin": "0:0:0:0:0:0:0:1, 50.152.174.195",
  "url": "http://localhost/put"
}
```

I think the reason that the Content-Length is not being shown in the spring cloud trace endpoint, is because at the point trace records the request - the header is not yet added - it only gets added later on once httpclient start processing it (and therefore hidden from the Zuul and Spring Cloud code).

Also, when I ran your sample app, I got the wire-level logging in stdout, which shows exactly what httpclient has sent over the wire too, eg:
```
2016-06-21 23:17:08.407 DEBUG 26197 --- [nio-8080-exec-9] org.apache.http.headers                  : http-outgoing-3 >> PUT /put HTTP/1.1
2016-06-21 23:17:08.407 DEBUG 26197 --- [nio-8080-exec-9] org.apache.http.headers                  : http-outgoing-3 >> user-agent: curl/7.48.0
2016-06-21 23:17:08.407 DEBUG 26197 --- [nio-8080-exec-9] org.apache.http.headers                  : http-outgoing-3 >> accept: */*
2016-06-21 23:17:08.407 DEBUG 26197 --- [nio-8080-exec-9] org.apache.http.headers                  : http-outgoing-3 >> content-type: text/plain
2016-06-21 23:17:08.407 DEBUG 26197 --- [nio-8080-exec-9] org.apache.http.headers                  : http-outgoing-3 >> x-forwarded-host: localhost
2016-06-21 23:17:08.407 DEBUG 26197 --- [nio-8080-exec-9] org.apache.http.headers                  : http-outgoing-3 >> x-forwarded-proto: http
2016-06-21 23:17:08.407 DEBUG 26197 --- [nio-8080-exec-9] org.apache.http.headers                  : http-outgoing-3 >> x-forwarded-prefix: /api/httpbin
2016-06-21 23:17:08.407 DEBUG 26197 --- [nio-8080-exec-9] org.apache.http.headers                  : http-outgoing-3 >> x-forwarded-port: 8080
2016-06-21 23:17:08.407 DEBUG 26197 --- [nio-8080-exec-9] org.apache.http.headers                  : http-outgoing-3 >> x-forwarded-for: 0:0:0:0:0:0:0:1
2016-06-21 23:17:08.407 DEBUG 26197 --- [nio-8080-exec-9] org.apache.http.headers                  : http-outgoing-3 >> Accept-Encoding: gzip
2016-06-21 23:17:08.407 DEBUG 26197 --- [nio-8080-exec-9] org.apache.http.headers                  : http-outgoing-3 >> Content-Length: 4
2016-06-21 23:17:08.407 DEBUG 26197 --- [nio-8080-exec-9] org.apache.http.headers                  : http-outgoing-3 >> Host: httpbin.org
2016-06-21 23:17:08.407 DEBUG 26197 --- [nio-8080-exec-9] org.apache.http.headers                  : http-outgoing-3 >> Connection: Keep-Alive
2016-06-21 23:17:08.407 DEBUG 26197 --- [nio-8080-exec-9] org.apache.http.wire                     : http-outgoing-3 >> "PUT /put HTTP/1.1[\r][\n]"
2016-06-21 23:17:08.407 DEBUG 26197 --- [nio-8080-exec-9] org.apache.http.wire                     : http-outgoing-3 >> "user-agent: curl/7.48.0[\r][\n]"
2016-06-21 23:17:08.407 DEBUG 26197 --- [nio-8080-exec-9] org.apache.http.wire                     : http-outgoing-3 >> "accept: */*[\r][\n]"
2016-06-21 23:17:08.407 DEBUG 26197 --- [nio-8080-exec-9] org.apache.http.wire                     : http-outgoing-3 >> "content-type: text/plain[\r][\n]"
2016-06-21 23:17:08.407 DEBUG 26197 --- [nio-8080-exec-9] org.apache.http.wire                     : http-outgoing-3 >> "x-forwarded-host: localhost[\r][\n]"
2016-06-21 23:17:08.407 DEBUG 26197 --- [nio-8080-exec-9] org.apache.http.wire                     : http-outgoing-3 >> "x-forwarded-proto: http[\r][\n]"
2016-06-21 23:17:08.407 DEBUG 26197 --- [nio-8080-exec-9] org.apache.http.wire                     : http-outgoing-3 >> "x-forwarded-prefix: /api/httpbin[\r][\n]"
2016-06-21 23:17:08.407 DEBUG 26197 --- [nio-8080-exec-9] org.apache.http.wire                     : http-outgoing-3 >> "x-forwarded-port: 8080[\r][\n]"
2016-06-21 23:17:08.407 DEBUG 26197 --- [nio-8080-exec-9] org.apache.http.wire                     : http-outgoing-3 >> "x-forwarded-for: 0:0:0:0:0:0:0:1[\r][\n]"
2016-06-21 23:17:08.407 DEBUG 26197 --- [nio-8080-exec-9] org.apache.http.wire                     : http-outgoing-3 >> "Accept-Encoding: gzip[\r][\n]"
2016-06-21 23:17:08.407 DEBUG 26197 --- [nio-8080-exec-9] org.apache.http.wire                     : http-outgoing-3 >> "Content-Length: 4[\r][\n]"
2016-06-21 23:17:08.408 DEBUG 26197 --- [nio-8080-exec-9] org.apache.http.wire                     : http-outgoing-3 >> "Host: httpbin.org[\r][\n]"
2016-06-21 23:17:08.408 DEBUG 26197 --- [nio-8080-exec-9] org.apache.http.wire                     : http-outgoing-3 >> "Connection: Keep-Alive[\r][\n]"
2016-06-21 23:17:08.408 DEBUG 26197 --- [nio-8080-exec-9] org.apache.http.wire                     : http-outgoing-3 >> "[\r][\n]"
2016-06-21 23:17:08.408 DEBUG 26197 --- [nio-8080-exec-9] org.apache.http.wire                     : http-outgoing-3 >> "blah"
```

So could you if the Content-Length (or if maybe a "Transfer-Encoding: chunked" header) is appearing in the org.apache.http.wire logging when you run your app through your ISP?

**Comment by beku8** [comment]
Hello @kerumai thanks for your time. You are right, trace endpoint was not accurate. There was no issue proxying to ```httpbin.org```. However there was an issue with the between zuul & eureka clients.

This turned out to be an issue not related to zuul per se, but a problem jersey library. ```com.sun.jersey.core.impl.provider.entity.InputStreamProvider```. 
```
    @Override
    public long getSize(InputStream t, Class<?> type, Type genericType, Annotation[] annotations, MediaType mediaType) {
        if (t instanceof ByteArrayInputStream)
            return ((ByteArrayInputStream)t).available();
        else 
            return -1;
    }
```
t is an instance of class com.netflix.zuul.http.ServletInputStreamWrapper not ByteArrayInputStream, therefore it returns -1. 

Thanks again for your advice how to debug, it helped to pinpoint the issue. Spring cloud had a way around it and committed a fix.

**Comment by mjsobremonte** [comment]
@beku8 do you have a link to the fix/workaround, or how can we pull it into our project?
We still keep getting "Transfer-Encoding: chunked" with spring-cloud-netflix:1.3.0.M1

**Comment by beku8** [comment]
It turned out to be a spring cloud issue
https://github.com/spring-cloud/spring-cloud-netflix/issues/1042
