### ISSUE TITLE
Zuul2: Routing without using Eureka service discovery

### ISSUE THREAD

**Issue by mmdemirbas** [Netflix/zuul#395]
Hello,

We want to use Zuul without service discovery, for instance, defining properties such as `zuul.routes.books.url = http://localhost:8090/books`, and routing accordingly with a custom filter. But, I can't figure out how to disable eureka and perform routing via custom filters. `zuul-core` has dependencies to `ribbon-eureka` and `eureka-client`, and disabling eureka seems impossible to me.
 
Is it possible? OR  Are you considering to release a zuul-without-eureka?

**Comment by spencergibb** [comment]
This is not the spring cloud Netflix issue tracker. There is no hard dependency between zuul core and eureka. It is successfully used with consul and zookeeper

**Comment by mmdemirbas** [comment]
But, I see these lines in build.gradle:

> compile "com.netflix.ribbon:ribbon-eureka:${versions_ribbon}"
> compile "com.netflix.eureka:eureka-client:latest.release"

I need to disable eureka service discovery completely. I don't want to use it. I want to handle routing in my custom filter, may be using simple properties like spring cloud Netflix, but definitely without using eureka.

**Comment by artgon** [comment]
Is this a Spring Zuul or Zuul 2 question?

Zuul 2 can be configured to use non-eureka endpoints. If you take a look at the new `2.1` branch. There is a configuration without Eureka routing in the sample app: https://github.com/Netflix/zuul/blob/2.1/zuul-sample/src/main/resources/application.properties#L43

**Comment by mmdemirbas** [comment]
It is a Zuul 2 question.

Even if I use that configuration, it still uses Ribbon load-balancer, right? But, I want to define service URLs directly as I said in the first message.

**Comment by artgon** [comment]
Yes, it will still use the ribbon load balancer (but not the client). You can set up your backends by specifying host and port in the `<client>.ribbon.DeploymentContextBasedVipAddresses` property. You can make as many backends as you want by changing that client prefix (set to `api` in the sample properties file). Then add some logic for routing the request in the Routes filter: https://github.com/Netflix/zuul/blob/2.1/zuul-sample/src/main/groovy/com/netflix/zuul/sample/filters/inbound/Routes.groovy#L55

**Comment by mmdemirbas** [comment]
OK. Now, routing succeeded. But, it seems that service discovery attempts continue in the background. (`eureka.validateInstanceId=false`)

```
2018-01-11 08:55:44,020 WARN  com.netflix.config.sources.URLConfigurationSource [main] No URLs will be polled as dynamic configuration sources.
2018-01-11 08:55:54,270 WARN  com.netflix.appinfo.AmazonInfo$Builder [main] Skipping the rest of AmazonInfo init as we were not able to load instanceId after the configured number of retries: 3, per fail fast configuration: true
2018-01-11 08:55:54,272 INFO  com.netflix.appinfo.RefreshableAmazonInfoProvider [main] Datacenter is: Amazon
2018-01-11 08:55:54,998 INFO  com.netflix.discovery.DiscoveryClient [main] Initializing Eureka in region us-east-1
2018-01-11 08:55:57,500 INFO  com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver [main] Resolving eureka endpoints via configuration
2018-01-11 08:55:57,507 WARN  com.netflix.discovery.endpoint.EndpointUtils [main] DISCOVERY: Could not pick a zone based on preferred zone settings. My zone - defaultZone, preferSameZone - false. Defaulting to defaultZone
2018-01-11 08:55:57,507 ERROR com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver [main] Cannot resolve to any endpoints from provided configuration: {defaultZone=[]}
2018-01-11 08:55:57,511 ERROR com.netflix.discovery.shared.transport.EurekaHttpClients [main] Initial resolution of Eureka server endpoints failed. Check ConfigClusterResolver logs for more info
```

And these lines printed every 30 seconds:

```
2018-01-11 08:56:57,722 INFO  com.netflix.discovery.DiscoveryClient [DiscoveryClient-CacheRefreshExecutor-0] Disable delta property : false
2018-01-11 08:56:57,722 INFO  com.netflix.discovery.DiscoveryClient [DiscoveryClient-CacheRefreshExecutor-0] Single vip registry refresh property : null
2018-01-11 08:56:57,722 INFO  com.netflix.discovery.DiscoveryClient [DiscoveryClient-CacheRefreshExecutor-0] Force full registry fetch : false
2018-01-11 08:56:57,722 INFO  com.netflix.discovery.DiscoveryClient [DiscoveryClient-CacheRefreshExecutor-0] Application is null : false
2018-01-11 08:56:57,723 INFO  com.netflix.discovery.DiscoveryClient [DiscoveryClient-CacheRefreshExecutor-0] Registered Applications size is zero : true
2018-01-11 08:56:57,723 INFO  com.netflix.discovery.DiscoveryClient [DiscoveryClient-CacheRefreshExecutor-0] Application version is -1: true
2018-01-11 08:56:57,723 INFO  com.netflix.discovery.DiscoveryClient [DiscoveryClient-CacheRefreshExecutor-0] Getting all instance registry info from the eureka server
2018-01-11 08:56:57,723 ERROR com.netflix.discovery.DiscoveryClient [DiscoveryClient-CacheRefreshExecutor-0] DiscoveryClient_ZUUL/192.168.1.177 - was unable to refresh its cache! status = There is no known eureka server; cluster server list is empty
com.netflix.discovery.shared.transport.TransportException: There is no known eureka server; cluster server list is empty
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:107)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137)
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
	at com.netflix.discovery.DiscoveryClient.getAndStoreFullRegistry(DiscoveryClient.java:1051)
	at com.netflix.discovery.DiscoveryClient.fetchRegistry(DiscoveryClient.java:965)
	at com.netflix.discovery.DiscoveryClient.refreshRegistry(DiscoveryClient.java:1471)
	at com.netflix.discovery.DiscoveryClient$CacheRefreshThread.run(DiscoveryClient.java:1438)
	at java.util.concurrent.Executors$RunnableAdapter.call$$$capture(Executors.java:511)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by artgon** [comment]
Try adding `eureka.shouldFetchRegistry=false` to your properties file.

**Comment by mmdemirbas** [comment]
Thank you, it works.

My configuration (`application.properties`) is below, in the case someone else needs it:

```
### Instance env settings

region=us-east-1
environment=test

## Eureka instance registration for this app

Name of the application to be identified by other services
eureka.name=zuul

The port where the service will be running and serving requests
eureka.port=7001

Virtual host name by which the clients identifies this service
eureka.vipAddress=${eureka.name}:${eureka.port}

For eureka clients running in eureka server, it needs to connect to servers in other zones
eureka.preferSameZone=false

 Don't register locally running instances.
eureka.registration.enabled=false

# Loading Filters
zuul.filters.root=zuul-sample/src/main/groovy/com/netflix/zuul/sample/filters
zuul.filters.locations=${zuul.filters.root}/inbound,${zuul.filters.root}/outbound,${zuul.filters.root}/endpoint
zuul.filters.packages=com.netflix.zuul.filters.common

##########################################
## Everything above included in the sample.
## Everything below added by me.
##########################################

api.ribbon.listOfServers=localhost:8090
api.ribbon.client.NIWSServerListClassName=com.netflix.loadbalancer.ConfigurationBasedServerList

eureka.validateInstanceId=false
eureka.shouldFetchRegistry=false

zuul.server.port.main=9090
```

And inside `Routes.apply()` method (`Routes` is an `HttpInboundSyncFilter` included in the sample):
```
SessionContext context = request.getContext()
context.setEndpoint(ZuulEndPointRunner.PROXY_ENDPOINT_FILTER_NAME);
context.setRouteVIP("api")
```

**Comment by sandy-adi** [comment]
@artgon I'd like to use Eureka but at the same time have the ability to override the upstream enroute

**Comment by qtwang** [comment]
@artgon We want to use Zuul with service discovery,but the error is as below:
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, java.lang.RuntimeException: Your datacenter is defined as cloud but we are not able to get the amazon metadata to register. 
Set the property eureka.validateInstanceId to false to ignore the metadata call
  while locating com.netflix.appinfo.providers.CloudInstanceConfigProvider
  while locating com.netflix.appinfo.CloudInstanceConfig
  while locating com.netflix.appinfo.EurekaInstanceConfig
    for the 1st parameter of com.netflix.appinfo.ApplicationInfoManager.<init>(ApplicationInfoManager.java:84)
  at com.netflix.appinfo.ApplicationInfoManager.class(ApplicationInfoManager.java:48)
  while locating com.netflix.appinfo.ApplicationInfoManager
    for the 1st parameter of com.netflix.netty.common.status.ServerStatusManager.<init>(ServerStatusManager.java:42)
  at com.netflix.zuul.sample.ZuulSampleModule.configure(ZuulSampleModule.java:59)
  while locating com.netflix.netty.common.status.ServerStatusManager
    for the 1st parameter of com.netflix.zuul.sample.SampleServerStartup.<init>(SampleServerStartup.java:81)
  at com.netflix.zuul.sample.SampleServerStartup.class(SampleServerStartup.java:68)
  while locating com.netflix.zuul.sample.SampleServerStartup
  while locating com.netflix.zuul.netty.server.BaseServerStartup
Caused by: java.lang.RuntimeException: Your datacenter is defined as cloud but we are not able to get the amazon metadata to register. 
I want to know how to config the eureka localhsot,thanks~

**Comment by therain123in** [comment]
> Thank you, it works.
> 
> My configuration (`application.properties`) is below, in the case someone else needs it:
> 
> ```
> ### Instance env settings
> 
> region=us-east-1
> environment=test
> 
> ## Eureka instance registration for this app
> 
> Name of the application to be identified by other services
> eureka.name=zuul
> 
> The port where the service will be running and serving requests
> eureka.port=7001
> 
> Virtual host name by which the clients identifies this service
> eureka.vipAddress=${eureka.name}:${eureka.port}
> 
> For eureka clients running in eureka server, it needs to connect to servers in other zones
> eureka.preferSameZone=false
> 
>  Don't register locally running instances.
> eureka.registration.enabled=false
> 
> # Loading Filters
> zuul.filters.root=zuul-sample/src/main/groovy/com/netflix/zuul/sample/filters
> zuul.filters.locations=${zuul.filters.root}/inbound,${zuul.filters.root}/outbound,${zuul.filters.root}/endpoint
> zuul.filters.packages=com.netflix.zuul.filters.common
> 
> ##########################################
> ## Everything above included in the sample.
> ## Everything below added by me.
> ##########################################
> 
> api.ribbon.listOfServers=localhost:8090
> api.ribbon.client.NIWSServerListClassName=com.netflix.loadbalancer.ConfigurationBasedServerList
> 
> eureka.validateInstanceId=false
> eureka.shouldFetchRegistry=false
> 
> zuul.server.port.main=9090
> ```
> 
> And inside `Routes.apply()` method (`Routes` is an `HttpInboundSyncFilter` included in the sample):
> 
> ```
> SessionContext context = request.getContext()
> context.setEndpoint(ZuulEndPointRunner.PROXY_ENDPOINT_FILTER_NAME);
> context.setRouteVIP("api")
> ```



> Thank you, it works.
> 
> My configuration (`application.properties`) is below, in the case someone else needs it:
> 
> ```
> ### Instance env settings
> 
> region=us-east-1
> environment=test
> 
> ## Eureka instance registration for this app
> 
> Name of the application to be identified by other services
> eureka.name=zuul
> 
> The port where the service will be running and serving requests
> eureka.port=7001
> 
> Virtual host name by which the clients identifies this service
> eureka.vipAddress=${eureka.name}:${eureka.port}
> 
> For eureka clients running in eureka server, it needs to connect to servers in other zones
> eureka.preferSameZone=false
> 
>  Don't register locally running instances.
> eureka.registration.enabled=false
> 
> # Loading Filters
> zuul.filters.root=zuul-sample/src/main/groovy/com/netflix/zuul/sample/filters
> zuul.filters.locations=${zuul.filters.root}/inbound,${zuul.filters.root}/outbound,${zuul.filters.root}/endpoint
> zuul.filters.packages=com.netflix.zuul.filters.common
> 
> ##########################################
> ## Everything above included in the sample.
> ## Everything below added by me.
> ##########################################
> 
> api.ribbon.listOfServers=localhost:8090
> api.ribbon.client.NIWSServerListClassName=com.netflix.loadbalancer.ConfigurationBasedServerList
> 
> eureka.validateInstanceId=false
> eureka.shouldFetchRegistry=false
> 
> zuul.server.port.main=9090
> ```
> 
> And inside `Routes.apply()` method (`Routes` is an `HttpInboundSyncFilter` included in the sample):
> 
> ```
> SessionContext context = request.getContext()
> context.setEndpoint(ZuulEndPointRunner.PROXY_ENDPOINT_FILTER_NAME);
> context.setRouteVIP("api")
> ```

Hi,
Can you please send the working sample code for the zuul load balancer without eureka ?
The links given in this page are not working. Its showing as 404 error.

**Comment by BigSully** [comment]
Just want a fast start of pure zuul server, here is how to make the zuul proxy **httpbin.org**:
```java
zuul.filters.root=/Users/james/zuul/zuul-sample/src/main/groovy/com/netflix/zuul/sample/filters

#api.ribbon.NIWSServerListClassName=com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
#api.ribbon.DeploymentContextBasedVipAddresses=api-test.netflix.net:7001


### Load balancing backends without Eureka

eureka.shouldFetchRegistry=false
eureka.validateInstanceId=false

api.ribbon.listOfServers=httpbin.org:80
api.ribbon.client.NIWSServerListClassName=com.netflix.loadbalancer.ConfigurationBasedServerList
#api.ribbon.DeploymentContextBasedVipAddresses=api-test.netflix.net:7001

zuul.server.port.main=9090
```

**Comment by SMakhrov** [comment]
@BigSully hi!
Could you help please - why is it doesn't work if url with multiple subdomains? 
Like this: test.s3-us-west-2.amazonaws.com:80

I see 301 Permanent redirect.
