### ISSUE TITLE
Error Connection via Websocket in Zuul 2.1 Sample App

### ISSUE THREAD

**Issue by vklein** [Netflix/zuul#418]
when i am trying to connect to a Websocket Server via Zuul 2.1 Sample App i get following error: 

`2018-03-29 13:39:51,919 INFO  ACCESS [Salamander-ClientToZuulWorker-0] 2018-03-29T13:39:51.911	0:0:0:0:0:0:0:1	9090	GET	/ws?debugRequest=true&encoding=text	101	7862	-	47d42be5-cec2-4a71-8dc5-3d81718c6f4a	"localhost:9090"	"-"	"-"	"-"	"-"	"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"	"-"	"-"	"-"
2018-03-29 13:39:51,919 INFO  com.netflix.netty.common.metrics.ServerChannelMetrics [Salamander-ClientToZuulWorker-0] Connection error caught. java.io.IOException: An established connection was aborted by the software in your host machine
java.io.IOException: An established connection was aborted by the software in your host machine
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:126)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2018-03-29 13:39:51,921 ERROR com.netflix.zuul.netty.filter.ZuulFilterChainHandler [Salamander-ClientToZuulWorker-0] zuul filter chain handler caught exception. cause=java.io.IOException: An established connection was aborted by the software in your host machine
java.io.IOException: An established connection was aborted by the software in your host machine
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:126)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2018-03-29 13:39:51,921 INFO  com.netflix.zuul.netty.server.ClientResponseWriter [Salamander-ClientToZuulWorker-0] ClientResponseWriter Received event io.netty.channel.socket.ChannelInputShutdownReadComplete@299ddcd4
`

Should the websocket connection already works in the current zuul 2.1 version?

Does somebody already uses zuul 2.1 for websocket connections?

**Comment by vklein** [comment]
Closed because websockets are not supported in the current version 2.1:
https://github.com/Netflix/zuul/issues/112#issuecomment-380174758
