### ISSUE TITLE
How do I call an external REST endpoint from a Zuul filter ?

### ISSUE THREAD

**Issue by nicolasduminil** [Netflix/zuul#512]
Hello, 
I have a Zuul service using automated mapping routes via service discovery. In one of the Zuul's route filter, I need to call the rest endpoint of an external service not registered with the discovery service.
 for example I need to invoke the endpoint http://192.19.0.9:8085/auth/accessToken. Then the following exception is raised:
com.netflix.zuul.exception.ZuulException: Filter threw Exception
 	at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:227) ~[zuul-core-1.3.0.jar!/:1.3.0]
 	at com.netflix.zuul.FilterProcessor.runFilters(FilterProcessor.java:157) ~[zuul-core-1.3.0.jar!/:1.3.0]
 	at com.netflix.zuul.FilterProcessor.route(FilterProcessor.java:118) ~[zuul-core-1.3.0.jar!/:1.3.0]
 	at com.netflix.zuul.ZuulRunner.route(ZuulRunner.java:96) ~[zuul-core-1.3.0.jar!/:1.3.0]
 	at com.netflix.zuul.http.ZuulServlet.route(ZuulServlet.java:116) ~[zuul-core-1.3.0.jar!/:1.3.0]
 	at com.netflix.zuul.http.ZuulServlet.service(ZuulServlet.java:81) ~[zuul-core-1.3.0.jar!/:1.3.0]
..............
Caused by: java.lang.IllegalStateException: No instances available for 192.19.0.9
 	at org.springframework.cloud.netflix.ribbon.RibbonLoadBalancerClient.execute(RibbonLoadBalancerClient.java:75) ~[spring-cloud-netflix-core-1.4.4.RELEASE.jar!/:1.4.4.RELEASE]
...
So, what happens obviously is that a mapping is looked up for the IP address 192.19.0.9 of the endpoint and nothing is found, of course. How could then I call this endpoint such that no mapping be applied ?

Many thanks in advance.
Nicolas

**Comment by nicolasduminil** [comment]
I forgot to share my Zuul configuration:
zuul:
  routes:
    ms-keycloak:
      path: /auth/**
      url: http://192.19.0.9:8085
Then calling  http://192.19.0.9:8085/auth/accessToken raises "No instances available for 192.19.0.9 and calling http://auth/accessToken raises "No instances available for auth".

**Comment by nicolasduminil** [comment]
Finally the correct way to invoke the endpoint is: http://hml-routing/auth/accessToken where hml-routing is the Eureka service ID of the Zuul service.
