### ISSUE TITLE
needsBodyBuffered() causes NullPointerException

### ISSUE THREAD

**Issue by danesavot** [Netflix/zuul#520]
I've got NulPointerException thrown when enabling needsBodyBufferred() with the following stack trace:

```
java.lang.NullPointerException
	at com.netflix.zuul.netty.filter.BaseZuulFilterRunner.initRunningFilterIndex(BaseZuulFilterRunner.java:88)
	at com.netflix.zuul.netty.filter.ZuulFilterChainRunner.filter(ZuulFilterChainRunner.java:52)
	at com.netflix.zuul.netty.filter.BaseZuulFilterRunner.invokeNextStage(BaseZuulFilterRunner.java:122)
	at com.netflix.zuul.netty.filter.ZuulEndPointRunner.filter(ZuulEndPointRunner.java:137)
	at com.netflix.zuul.netty.filter.ZuulEndPointRunner.filter(ZuulEndPointRunner.java:49)
	at com.netflix.zuul.netty.filter.BaseZuulFilterRunner.invokeNextStage(BaseZuulFilterRunner.java:112)
	at com.netflix.zuul.netty.filter.ZuulFilterChainRunner.filter(ZuulFilterChainRunner.java:115)
	at com.netflix.zuul.netty.filter.ZuulFilterChainHandler.channelRead(ZuulFilterChainHandler.java:84)
```

Ex:
```
public class GitHubEndpoint extends HttpAsyncEndpoint {

    @Override
    public Observable<HttpResponseMessage> applyAsync(HttpRequestMessage request) {

        return GitHubService.listRepos("danesavot");
          
    @Override
    public boolean needsBodyBuffered(HttpRequestMessage input) {
        return true;
    }
}
```

**Comment by artgon** [comment]
You can buffer a body on an `Endpoint` filter.

**Comment by rafaelGuerreiro** [comment]
I'm having the exact same problem.

I needed an Async endpoint, which I think Zuul2 doesn't provide, and it needs to read the body of the request.

I also tried copying the workflow from Zuul's HttpSyncEndpoint, but they still cause the body to be unavailable to my endpoint.

@danesavot do you have any workaround that you implemented? As this issue is almost 2 years old, now.

**Comment by danesavot** [comment]
Yeah, i think I have.
You need to create an InBoundFilter and override needsBodyBuffered() so that Zull will buffer the body for the Endpoint and avoid above NPE. Let me know if you need further clarification :)

**Comment by rafaelGuerreiro** [comment]
Thank you @danesavot, it works like a charm.

Just to provide more context to Zuul's team of why this is needed: I have a framework that I made it use Observable to be able to use it in the filters. But some of the Proxy operations require the Proxy itself to access and persist the information, and I'd love to see it using the same framework.
