### ISSUE TITLE
Zuul Routing - Connection Issue communicating with Upstream System - Large Response Payloads

### ISSUE THREAD

**Issue by brijeshparashar** [Netflix/zuul#540]
Hi All, 

We are encountering exceptions while trying to hit a Zuul Router via F5 Load balancer when the response payload is large (No issue for smaller payloads (or) hitting the Zull outer directly without F5 Load Balancer for larger payloads as well)
The architechture is F5-> Zuul Router(SpringBoot Service) -> DownStream System(Java application)

The exception being thrown by F5 is as below

`    <head>
        <title>502 Bad Gateway</title>
    </head>
    <body>
        <h1>Bad Gateway</h1>
        <p>The proxy server received an invalid
response from an upstream server.
            <br />
        </p>
    </body>`

----------------------------------------------------------------------------------------
On checking the logs we found that the response is reaching to Zuul Router from the downstream system but it is failing while returning the respnse to the upstream system ( in our case F5) 

Below is the error being logged in this scenario in Zuul Router. (FULL STACKTRACE ATTACHED)
[FullStackTrace.txt](https://github.com/Netflix/zuul/files/2678821/FullStackTrace.txt)

   Caused by: org.springframework.cloud.netflix.zuul.util.ZuulRuntimeException: com.netflix.zuul.exception.ZuulException: java.io.IOException: An existing connection was forcibly closed by the remote host
               at com.au.comp.filter.RouterSendErrorFilter.run(RouterSendErrorFilter.java:75) ~[classes!/:na]
               at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:117) ~[zuul-core-1.3.1.jar!/:1.3.1]
               at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:193) ~[zuul-core-1.3.1.jar!/:1.3.1]
               ... 51 common frames omitted

------------------------------------------------------------------------------------------

Below is the configuration of Zuul Router. 

ribbon:
  eureka:
    enabled: false
  eager-load:
    enabled: true
    clients: testClient

zuul:
  include-debug-header: false
  debug:
    request: false
  routes:
    thirdMan:
      path: /test/Service
      sensitiveHeaders:
      serviceId: test-service

test-service:
   ribbon:
     NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
     NFLoadBalancerRuleClassName: com.au.comp.rule.AvailabilityBasedServerSelectionRule
     NFLoadBalancerPingClassName: com.netflix.loadbalancer.PingUrl
     listOfServers: http://localhost:8080
     ServerListRefreshInterval: 15000
     **ConnectTimeout: 180000
     ReadTimeout: 180000**

Can you please let us know what could have been the root cause of the issue and the possible solution to the same. Does it have anything to do with configuration of timeouts at Router's end. The existing timeouts that we have configured are highlighted in bold above.

**Comment by artgon** [comment]
Please direct your question to the spring boot project.

**Comment by brijeshparashar** [comment]
Hi 

This issue is happening while overriding Zuul filters. 
After further analysis I found that some headers including the *transfer-encoding* are removed while writing the response back to the upstream. This is done in ProxyRequestHelper class in zuul. 

But because we have overridden the SendResponseFilter and havent excluded these headers as done by Zuul internally we were facing that issue while writing the response back to upstream. After excluding the header transfer-encoding everything worked fine. 

Could you let us know why do we need to exclude these headers ? 

Thanks.
