### ISSUE TITLE
Zuul 2.0 Server startup fails after enabling HTTP2 when run as a JAR

### ISSUE THREAD

**Issue by ronisac** [Netflix/zuul#577]
Hi,

I have built up a Zuul2 server which is up and running in my local with HTTP2 enabled (using IDE).
It is a maven project and loading of certificates works fine in my local.
But when I have built the same java application into JAR, the certificate loading and server startup fails with the following exception.
```
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) postConstruct failed
  at com.sapient.rc.zuul.core.SampleServerStartup.class(SampleServerStartup.java:57)
  while locating com.sapient.rc.zuul.core.SampleServerStartup
  while locating com.netflix.zuul.netty.server.BaseServerStartup

1 error
        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226)
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1053)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1086)
        at com.netflix.governator.DelegatingInjector.getInstance(DelegatingInjector.java:88)
        at com.sapient.rc.zuul.core.Bootstrap.start(Bootstrap.java:50)
        at com.sapient.rc.zuul.core.Bootstrap.main(Bootstrap.java:34)
Caused by: java.lang.RuntimeException: Error configuring SslContext!
        at com.netflix.zuul.netty.ssl.BaseSslContextFactory.createBuilderForServer(BaseSslContextFactory.java:100)
        at com.netflix.zuul.netty.server.http2.Http2Configuration.configureSSL(Http2Configuration.java:35)
        at com.netflix.zuul.netty.server.http2.Http2SslChannelInitializer.<init>(Http2SslChannelInitializer.java:60)
        at com.sapient.rc.zuul.core.SampleServerStartup.choosePortsAndChannels(SampleServerStartup.java:131)
        at com.netflix.zuul.netty.server.BaseServerStartup.init(BaseServerStartup.java:107)
        at com.netflix.governator.internal.JSR250LifecycleAction.call(JSR250LifecycleAction.java:83)
        at com.netflix.governator.ManagedInstanceAction.call(ManagedInstanceAction.java:34)
        at com.netflix.governator.LifecycleModule$LifecycleProvisionListener.onProvision(LifecycleModule.java:175)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:127)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1050)
        ... 4 more
Caused by: java.io.FileNotFoundException: file:\C:\Projects\XXX\XXX\Code\Zuul2\zuul2-maven\target\zuul2-0.0.1-SNAPSHOT-jar-with-dependencies.jar!\ssl\star.xxxx.io.crt (The filename, directory name, or volume label syntax is incorrect)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at com.netflix.zuul.netty.ssl.BaseSslContextFactory.createBuilderForServer(BaseSslContextFactory.java:83)
        ... 21 more
###############
Zuul Sample: initialization failed. Forcing shutdown now.
###############
```

**Comment by ronisac** [comment]
Apparently BaseSslContextFactory (com.netflix.zuul.netty.ssl) is getting certificate files as "File" object from serverSslConfig object. As per suggestions in the stackoverflow, the certificate files should be loaded as InputStream instead of File object which leads into changing the Zuul2 library files. Please let me know if somebody has any other solutions for this issue.

**Comment by ronisac** [comment]
Can anybody please help me resolving this issue who has enabled HTTP2 in Zuul2 server? I am trying to deploy my Zuul2 server as a JAR and the server startup is failing.

**Comment by ronisac** [comment]
I had to extend BaseSslContextFactory to read the certificate files as a stream (ClassLoader.getSystemResourceAsStream()) instead of ClassLoader.getSystemResource(). I could resolve the issue.

**Comment by ronisac** [comment]
Is it possible to enable both HTTP2 and SSE in Zuul2. As per Sample Application, it is a switch case. Is it possible to enable the same using properties than in the code. Zuul2 wiki seems missing those details.

**Comment by xletme** [comment]
Hi ! I have met the same problem with you,could you resolve the problem you issue?
