### ISSUE TITLE
 WARN com.netflix.zuul.netty.server.DirectMemoryMonitor - Error in DirectMemoryMonitor task.

### ISSUE THREAD

**Issue by shaoqinhe** [Netflix/zuul#641]
```
[pool-5-thread-1] WARN com.netflix.zuul.netty.server.DirectMemoryMonitor - Error in DirectMemoryMonitor task.
java.lang.NullPointerException
	at com.netflix.servo.monitor.LongGauge.set(LongGauge.java:42)
	at com.netflix.zuul.netty.server.DirectMemoryMonitor$Task.run(DirectMemoryMonitor.java:78)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

请问 DirectMemoryMonitor类里面的
Field maxMemory = c.getDeclaredField("DIRECT_MEMORY_LIMIT") && 
Field reservedMemory = c.getDeclaredField("DIRECT_MEMORY_COUNTER")
的值是哪里获取的，为甚么一直为空？

**Comment by carl-mastrangelo** [comment]
@shaoqinhe What JDK version are you using?

**Comment by shaoqinhe** [comment]
The version is jdk1.8.0_191

**Comment by GitJelly** [comment]
I am facing the same problem. Any solutions to it?

**Comment by artgon** [comment]
I can't repro this. Do you have steps?

**Comment by roycebranning** [comment]
had this same error (although I was using jdk 11). i was using zuul-core 2.1.4, updating to 2.1.8 fixed it.

I believe [this commit](https://github.com/Netflix/zuul/commit/6189058ab674e8a3ff4388787fa6e844022ca7a3#diff-385e7068eb0ac5e149baf883731b605f444a21196153bb979b1d7e9780034d61) was responsible for the fix.
