### ISSUE TITLE
Access is denied

### ISSUE THREAD

**Issue by chenlinks** [Netflix/zuul#709]
I use zuul 、oauth and jwt  to  construct  a sso system,  An error was reported when requesting the application interface

**zuul  config:**

spring:
  application:
    name: zuul-server

server:
  port: 5555
  use-forward-headers: true

eureka:
  client:
    serviceUrl:
      defaultZone: "http://admin:epxing@${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka"
  instance:
    prefer-ip-address: true

zuul:
  routes:
    client-a:
      path: /demo/**
      serviceId: client-demo
    auth-server:
      path: /auth/**
      serviceId: auth-server
      stripPrefix: true
  sensitive-headers: Cookie,Set-Cookie

security:
  oauth2:
    client:
      access-token-uri: http://localhost:7777/auth/oauth/token
      user-authorization-uri: http://localhost:7777/auth/oauth/authorize
      client-id: epxing-auth
      client-secret: epxing
#      grant-type: password
      grant-type: authorization_code
    resource:
      jwt:
        key-value: epxing
    sso:
      login-path: /auth-server/auth/login
    authorization:
      check-token-access:  http://localhost:7777/auth/oauth/check_token

logging:
  level:
    org.springframework.security: debug
    com.netflix: DEBUG

# logback日志配置,日志环境类型，服务名，级别
log.env.profile: dev
log.env.module: epxing-zuul
log.env.logger.level: info

WebSecurityConfigurerAdapter   config:

@Configuration
@Order(1)
@EnableWebSecurity
@EnableOAuth2Sso
public class ZuulWebSecurityConfigurerAdapter extends WebSecurityConfigurerAdapter {

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http
                .authorizeRequests()
                .antMatchers(BaseConstants.LOGIN_URL,"/auth-server/auth/**")
                .permitAll()
                .anyRequest()
                .authenticated()
                .and()
                .csrf()
                .disable()
                .sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS).and()
                // 退出的URL是/logout
                .logout().logoutUrl(BaseConstants.LOGOUT_URL).permitAll()
                // 退出成功后，跳转到/路径。
                .logoutSuccessUrl(BaseConstants.LOGIN_URL).permitAll();
    }

}

ERROR:
2020-01-18 11:19:57.973 DEBUG 17284 --- [nio-5555-exec-5] o.s.s.w.a.ExceptionTranslationFilter     : Calling Authentication entry point.
2020-01-18 11:19:57.973 DEBUG 17284 --- [nio-5555-exec-5] o.s.s.w.a.Http403ForbiddenEntryPoint     : Pre-authenticated entry point called. Rejecting access
2020-01-18 11:19:57.973 DEBUG 17284 --- [nio-5555-exec-5] o.s.s.w.header.writers.HstsHeaderWriter  : Not injecting HSTS header since it did not match the requestMatcher org.springframework.security.web.header.writers.HstsHeaderWriter$SecureRequestMatcher@67b2fa23
2020-01-18 11:19:57.973 DEBUG 17284 --- [nio-5555-exec-5] s.s.w.c.SecurityContextPersistenceFilter : SecurityContextHolder now cleared, as request processing completed
2020-01-18 11:19:57.974 DEBUG 17284 --- [nio-5555-exec-5] o.s.security.web.FilterChainProxy        : /error at position 1 of 10 in additional filter chain; firing Filter: 'WebAsyncManagerIntegrationFilter'
2020-01-18 11:19:57.974 DEBUG 17284 --- [nio-5555-exec-5] o.s.security.web.FilterChainProxy        : /error at position 2 of 10 in additional filter chain; firing Filter: 'SecurityContextPersistenceFilter'
2020-01-18 11:19:57.974 DEBUG 17284 --- [nio-5555-exec-5] o.s.security.web.FilterChainProxy        : /error at position 3 of 10 in additional filter chain; firing Filter: 'HeaderWriterFilter'
2020-01-18 11:19:57.974 DEBUG 17284 --- [nio-5555-exec-5] o.s.security.web.FilterChainProxy        : /error at position 4 of 10 in additional filter chain; firing Filter: 'LogoutFilter'
2020-01-18 11:19:57.974 DEBUG 17284 --- [nio-5555-exec-5] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/auth-server/auth/logout', GET]
2020-01-18 11:19:57.974 DEBUG 17284 --- [nio-5555-exec-5] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/error'; against '/auth-server/auth/logout'
2020-01-18 11:19:57.974 DEBUG 17284 --- [nio-5555-exec-5] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/auth-server/auth/logout', POST]
2020-01-18 11:19:57.974 DEBUG 17284 --- [nio-5555-exec-5] o.s.s.w.u.matcher.AntPathRequestMatcher  : Request 'GET /error' doesn't match 'POST /auth-server/auth/logout
2020-01-18 11:19:57.974 DEBUG 17284 --- [nio-5555-exec-5] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/auth-server/auth/logout', PUT]
2020-01-18 11:19:57.975 DEBUG 17284 --- [nio-5555-exec-5] o.s.s.w.u.matcher.AntPathRequestMatcher  : Request 'GET /error' doesn't match 'PUT /auth-server/auth/logout
2020-01-18 11:19:57.975 DEBUG 17284 --- [nio-5555-exec-5] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/auth-server/auth/logout', DELETE]
2020-01-18 11:19:57.975 DEBUG 17284 --- [nio-5555-exec-5] o.s.s.w.u.matcher.AntPathRequestMatcher  : Request 'GET /error' doesn't match 'DELETE /auth-server/auth/logout
2020-01-18 11:19:57.976 DEBUG 17284 --- [nio-5555-exec-5] o.s.s.web.util.matcher.OrRequestMatcher  : No matches found
2020-01-18 11:19:57.976 DEBUG 17284 --- [nio-5555-exec-5] o.s.security.web.FilterChainProxy        : /error at position 5 of 10 in additional filter chain; firing Filter: 'RequestCacheAwareFilter'
2020-01-18 11:19:57.976 DEBUG 17284 --- [nio-5555-exec-5] o.s.security.web.FilterChainProxy        : /error at position 6 of 10 in additional filter chain; firing Filter: 'SecurityContextHolderAwareRequestFilter'
2020-01-18 11:19:57.976 DEBUG 17284 --- [nio-5555-exec-5] o.s.security.web.FilterChainProxy        : /error at position 7 of 10 in additional filter chain; firing Filter: 'AnonymousAuthenticationFilter'
2020-01-18 11:19:57.976 DEBUG 17284 --- [nio-5555-exec-5] o.s.s.w.a.AnonymousAuthenticationFilter  : Populated SecurityContextHolder with anonymous token: 'org.springframework.security.authentication.AnonymousAuthenticationToken@4cf514ec: Principal: anonymousUser; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@fffde5d4: RemoteIpAddress: 0:0:0:0:0:0:0:1; SessionId: CB34F498A8C8BD410F1866FC2DCAECE9; Granted Authorities: ROLE_ANONYMOUS'
2020-01-18 11:19:57.976 DEBUG 17284 --- [nio-5555-exec-5] o.s.security.web.FilterChainProxy        : /error at position 8 of 10 in additional filter chain; firing Filter: 'SessionManagementFilter'
2020-01-18 11:19:57.976 DEBUG 17284 --- [nio-5555-exec-5] o.s.security.web.FilterChainProxy        : /error at position 9 of 10 in additional filter chain; firing Filter: 'ExceptionTranslationFilter'
2020-01-18 11:19:57.976 DEBUG 17284 --- [nio-5555-exec-5] o.s.security.web.FilterChainProxy        : /error at position 10 of 10 in additional filter chain; firing Filter: 'FilterSecurityInterceptor'
2020-01-18 11:19:57.976 DEBUG 17284 --- [nio-5555-exec-5] o.s.security.web.FilterChainProxy        : /error reached end of additional filter chain; proceeding with original chain
2020-01-18 11:19:57.979 DEBUG 17284 --- [nio-5555-exec-5] o.s.s.w.a.ExceptionTranslationFilter     : Chain processed normally
2020-01-18 11:19:57.980 DEBUG 17284 --- [nio-5555-exec-5] s.s.w.c.SecurityContextPersistenceFilter : SecurityContextHolder now cleared, as request processing completed
2020-01-18 11:19:58.982 DEBUG 17284 --- [nio-5555-exec-6] o.s.security.web.FilterChainProxy        : /client-demo/api/product/1 at position 1 of 10 in additional filter chain; firing Filter: 'WebAsyncManagerIntegrationFilter'
2020-01-18 11:19:58.983 DEBUG 17284 --- [nio-5555-exec-6] o.s.security.web.FilterChainProxy        : /client-demo/api/product/1 at position 2 of 10 in additional filter chain; firing Filter: 'SecurityContextPersistenceFilter'
2020-01-18 11:19:58.983 DEBUG 17284 --- [nio-5555-exec-6] o.s.security.web.FilterChainProxy        : /client-demo/api/product/1 at position 3 of 10 in additional filter chain; firing Filter: 'HeaderWriterFilter'
2020-01-18 11:19:58.983 DEBUG 17284 --- [nio-5555-exec-6] o.s.security.web.FilterChainProxy        : /client-demo/api/product/1 at position 4 of 10 in additional filter chain; firing Filter: 'LogoutFilter'
2020-01-18 11:19:58.983 DEBUG 17284 --- [nio-5555-exec-6] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/auth-server/auth/logout', GET]
2020-01-18 11:19:58.983 DEBUG 17284 --- [nio-5555-exec-6] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/client-demo/api/product/1'; against '/auth-server/auth/logout'
2020-01-18 11:19:58.983 DEBUG 17284 --- [nio-5555-exec-6] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/auth-server/auth/logout', POST]
2020-01-18 11:19:58.983 DEBUG 17284 --- [nio-5555-exec-6] o.s.s.w.u.matcher.AntPathRequestMatcher  : Request 'GET /client-demo/api/product/1' doesn't match 'POST /auth-server/auth/logout
2020-01-18 11:19:58.983 DEBUG 17284 --- [nio-5555-exec-6] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/auth-server/auth/logout', PUT]
2020-01-18 11:19:58.983 DEBUG 17284 --- [nio-5555-exec-6] o.s.s.w.u.matcher.AntPathRequestMatcher  : Request 'GET /client-demo/api/product/1' doesn't match 'PUT /auth-server/auth/logout
2020-01-18 11:19:58.983 DEBUG 17284 --- [nio-5555-exec-6] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/auth-server/auth/logout', DELETE]
2020-01-18 11:19:58.983 DEBUG 17284 --- [nio-5555-exec-6] o.s.s.w.u.matcher.AntPathRequestMatcher  : Request 'GET /client-demo/api/product/1' doesn't match 'DELETE /auth-server/auth/logout
2020-01-18 11:19:58.983 DEBUG 17284 --- [nio-5555-exec-6] o.s.s.web.util.matcher.OrRequestMatcher  : No matches found
2020-01-18 11:19:58.983 DEBUG 17284 --- [nio-5555-exec-6] o.s.security.web.FilterChainProxy        : /client-demo/api/product/1 at position 5 of 10 in additional filter chain; firing Filter: 'RequestCacheAwareFilter'
2020-01-18 11:19:58.983 DEBUG 17284 --- [nio-5555-exec-6] o.s.security.web.FilterChainProxy        : /client-demo/api/product/1 at position 6 of 10 in additional filter chain; firing Filter: 'SecurityContextHolderAwareRequestFilter'
2020-01-18 11:19:58.984 DEBUG 17284 --- [nio-5555-exec-6] o.s.security.web.FilterChainProxy        : /client-demo/api/product/1 at position 7 of 10 in additional filter chain; firing Filter: 'AnonymousAuthenticationFilter'
2020-01-18 11:19:58.984 DEBUG 17284 --- [nio-5555-exec-6] o.s.s.w.a.AnonymousAuthenticationFilter  : Populated SecurityContextHolder with anonymous token: 'org.springframework.security.authentication.AnonymousAuthenticationToken@4cf514ec: Principal: anonymousUser; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@fffde5d4: RemoteIpAddress: 0:0:0:0:0:0:0:1; SessionId: CB34F498A8C8BD410F1866FC2DCAECE9; Granted Authorities: ROLE_ANONYMOUS'
2020-01-18 11:19:58.984 DEBUG 17284 --- [nio-5555-exec-6] o.s.security.web.FilterChainProxy        : /client-demo/api/product/1 at position 8 of 10 in additional filter chain; firing Filter: 'SessionManagementFilter'
2020-01-18 11:19:58.984 DEBUG 17284 --- [nio-5555-exec-6] o.s.security.web.FilterChainProxy        : /client-demo/api/product/1 at position 9 of 10 in additional filter chain; firing Filter: 'ExceptionTranslationFilter'
2020-01-18 11:19:58.984 DEBUG 17284 --- [nio-5555-exec-6] o.s.security.web.FilterChainProxy        : /client-demo/api/product/1 at position 10 of 10 in additional filter chain; firing Filter: 'FilterSecurityInterceptor'
2020-01-18 11:19:58.985 DEBUG 17284 --- [nio-5555-exec-6] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/auth-server/auth/logout', GET]
2020-01-18 11:19:58.985 DEBUG 17284 --- [nio-5555-exec-6] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/client-demo/api/product/1'; against '/auth-server/auth/logout'
2020-01-18 11:19:58.985 DEBUG 17284 --- [nio-5555-exec-6] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/auth-server/auth/logout', POST]
2020-01-18 11:19:58.985 DEBUG 17284 --- [nio-5555-exec-6] o.s.s.w.u.matcher.AntPathRequestMatcher  : Request 'GET /client-demo/api/product/1' doesn't match 'POST /auth-server/auth/logout
2020-01-18 11:19:58.985 DEBUG 17284 --- [nio-5555-exec-6] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/auth-server/auth/logout', PUT]
2020-01-18 11:19:58.985 DEBUG 17284 --- [nio-5555-exec-6] o.s.s.w.u.matcher.AntPathRequestMatcher  : Request 'GET /client-demo/api/product/1' doesn't match 'PUT /auth-server/auth/logout
2020-01-18 11:19:58.985 DEBUG 17284 --- [nio-5555-exec-6] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/auth-server/auth/logout', DELETE]
2020-01-18 11:19:58.985 DEBUG 17284 --- [nio-5555-exec-6] o.s.s.w.u.matcher.AntPathRequestMatcher  : Request 'GET /client-demo/api/product/1' doesn't match 'DELETE /auth-server/auth/logout
2020-01-18 11:19:58.985 DEBUG 17284 --- [nio-5555-exec-6] o.s.s.web.util.matcher.OrRequestMatcher  : No matches found
2020-01-18 11:19:58.985 DEBUG 17284 --- [nio-5555-exec-6] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/client-demo/api/product/1'; against '/auth-server/auth/login'
2020-01-18 11:19:58.985 DEBUG 17284 --- [nio-5555-exec-6] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/client-demo/api/product/1'; against '/auth-server/auth/**'
2020-01-18 11:19:58.985 DEBUG 17284 --- [nio-5555-exec-6] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/client-demo/api/product/1'; against '/auth-server/auth/oauth/token'
2020-01-18 11:19:58.985 DEBUG 17284 --- [nio-5555-exec-6] o.s.s.w.a.i.FilterSecurityInterceptor    : Secure object: FilterInvocation: URL: /client-demo/api/product/1; Attributes: [authenticated]
2020-01-18 11:19:58.985 DEBUG 17284 --- [nio-5555-exec-6] o.s.s.w.a.i.FilterSecurityInterceptor    : Previously Authenticated: org.springframework.security.authentication.AnonymousAuthenticationToken@4cf514ec: Principal: anonymousUser; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@fffde5d4: RemoteIpAddress: 0:0:0:0:0:0:0:1; SessionId: CB34F498A8C8BD410F1866FC2DCAECE9; Granted Authorities: ROLE_ANONYMOUS
2020-01-18 11:19:58.985 DEBUG 17284 --- [nio-5555-exec-6] o.s.s.access.vote.AffirmativeBased       : Voter: org.springframework.security.web.access.expression.WebExpressionVoter@97e3295, returned: -1
2020-01-18 11:19:58.986 DEBUG 17284 --- [nio-5555-exec-6] o.s.s.w.a.ExceptionTranslationFilter     : Access is denied (user is anonymous); redirecting to authentication entry point

org.springframework.security.access.AccessDeniedException: Access is denied
	at org.springframework.security.access.vote.AffirmativeBased.decide(AffirmativeBased.java:84)
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:233)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:124)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.oauth2.client.filter.OAuth2ClientContextFilter.doFilter(OAuth2ClientContextFilter.java:60)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:155)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:123)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:108)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:685)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

Request with token，postman back info:

{
    "timestamp": "2020-01-18T03:28:31.127+0000",
    "status": 403,
    "error": "Forbidden",
    "message": "Access Denied",
    "path": "/client-demo/api/product/1"
}

**Comment by vishwasmandpe** [comment]
were you able to resolve this issue? I am facing the same issue.

**Comment by nimble00** [comment]
I'm also facing the same issue. And I've sadly wasted a whole day trying to fix this.

**Comment by yangjilong2000** [comment]
i am also facing the same issue
