### ISSUE TITLE
Problem when using HTTP methods other than GET with zuul-netflix-webapp

### ISSUE THREAD

**Issue by bondj** [Netflix/zuul#8]
Hi,

When I tried using zuul-netflix-webapp I hit a problem, when logging in to my application. This was the first POST request, and the following error message was logged.

ERROR 23:40:24,663 Filter threw Exception
com.netflix.zuul.exception.ZuulException: Filter threw Exception
        at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:196)
        at com.netflix.zuul.FilterProcessor.runFilters(FilterProcessor.java:147)
        at com.netflix.zuul.FilterProcessor.route(FilterProcessor.java:106)
        at com.netflix.zuul.ZuulRunner.route(ZuulRunner.java:78)
        at com.netflix.zuul.http.ZuulServlet.route(ZuulServlet.java:104)
        at com.netflix.zuul.http.ZuulServlet.service(ZuulServlet.java:69)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
        at com.google.inject.servlet.DefaultFilterPipeline.dispatch(DefaultFilterPipeline.java:43)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at com.netflix.zuul.context.ContextLifecycleFilter.doFilter(ContextLifecycleFilter.java:40)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:440)
        at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)
        at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:943)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410)
        at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Caused by: groovy.lang.MissingPropertyException: No such property: Verb for class: com.netflix.niws.client.http.RestClient
        at groovy.lang.MetaClassImpl.invokeStaticMissingProperty(MetaClassImpl.java:895)
        at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1605)
        at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1581)
        at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:3326)
        at org.codehaus.groovy.runtime.callsite.ClassMetaClassGetPropertySite.getProperty(ClassMetaClassGetPropertySite.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:227)
        at scripts.routing.ZuulNFRequest.getVerb(ZuulNFRequest.groovy:228)
        at scripts.routing.ZuulNFRequest.getVerb(ZuulNFRequest.groovy:222)
        at scripts.routing.ZuulNFRequest$getVerb.callCurrent(Unknown Source)
        at scripts.routing.ZuulNFRequest.run(ZuulNFRequest.groovy:79)
        at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:114)
        at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:175)
        ... 28 more

Taking a sneaky peek at the groovy script, it appears that ZuulNFRequest.groovy lines 228-232 should not reference the field Verb in RestClient and instead just reference the Verb enum imported from HttpClientRequest. 

When I made this change it worked fine.

**Comment by NiteshKant** [comment]
[The code](https://github.com/Netflix/zuul/blob/1.x/zuul-netflix-webapp/src/main/groovy/filters/route/ZuulNFRequest.groovy#L227) looks fine now. Closing.
