### ISSUE TITLE
IllegalArgumentException in ProxyEndpoint in operationComplete()

### ISSUE THREAD

**Issue by kelnos** [Netflix/zuul#897]
I've been working on upgrading us from Zuul 2.1.7 and 2.1.8, and I'm hitting an issue.  When running a request through the filter chain, it hits `ProxyEndpoint` but fails with:

```
[Salamander-ClientToZuulWorker-0] ERROR com.netflix.zuul.filters.endpoint.ProxyEndpoint - Uncaught error in operationComplete(). Closing the server channel now. Channel: [id: 0x63a604c3, L:/127.0.0.1:17001 - R:/127.0.0.1:43344], active=true, open=true, registered=true, writable=true, id=63a604c3, Passport: CurrentPassport {start_ms=1600998759706, [+0=SERVER_CH_ACTIVE, +9382628=IN_REQ_HEADERS_RECEIVED, +44611188=FILTERS_INBOUND_START, +100925498=IN_REQ_LAST_CONTENT_RECEIVED, +777519202=FILTERS_INBOUND_END, +1375460770=ORIGIN_CH_CONNECTING, +1383996001=ORIGIN_CONN_ACQUIRE_START, +1394877234=ORIGIN_CH_CONNECTED, +1397396640=NOW]}
java.lang.IllegalArgumentException: Value may not be null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:135)
	at com.netflix.client.config.ReloadableClientConfig.setProperty(ReloadableClientConfig.java:387)
	at com.netflix.zuul.filters.endpoint.ProxyEndpoint.lambda$operationComplete$2(ProxyEndpoint.java:480)
	at com.netflix.zuul.netty.server.MethodBinding.bind(MethodBinding.java:42)
	at com.netflix.zuul.filters.endpoint.ProxyEndpoint.operationComplete(ProxyEndpoint.java:445)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:96)
	at com.netflix.zuul.netty.connectionpool.PerServerConnectionPool.createConnection(PerServerConnectionPool.java:336)
	at com.netflix.zuul.netty.connectionpool.PerServerConnectionPool.handleConnectCompletion(PerServerConnectionPool.java:317)
	at com.netflix.zuul.netty.connectionpool.PerServerConnectionPool.lambda$tryMakingNewConnection$0(PerServerConnectionPool.java:268)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.fulfillConnectPromise(AbstractEpollChannel.java:615)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:653)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:529)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:465)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

It looks like if the `ReadTimeout` isn't specified, `ProxyEndpoint` does something not allowed at https://github.com/Netflix/zuul/blob/v2.1.8/zuul-core/src/main/java/com/netflix/zuul/filters/endpoint/ProxyEndpoint.java#L480 -- `null` is not valid to pass to `setProperty()`, because `ReloadableClientConfig.setProperty()` does a precondition check to ensure that argument is not `null`.

Strangely, I can't seem to work around this by setting `$VIPNAME.ribbon.ReadTimeout` in my app properties file... for some reason it still hits that `if` branch and throws.  Looking at how it's fetching the config for that value, I think it might need to be specified in some other way, but I can't seem to figure out how.

**Comment by quannguyen22** [comment]
I’m dealing with the same problem as you.

**Comment by carl-mastrangelo** [comment]
@artgon  @jfernandez  I seem to recall timeout behavior being modified with regards to null recently.

**Comment by artgon** [comment]
This should be fixed by PR #898

**Comment by artgon** [comment]
I'll also release 2.1.9

**Comment by kelnos** [comment]
2.1.9 is working great, thanks!
